services:
  - type: web
    name: flujo-dinamico-telegram
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: CHAT_ID
        sync: false
      - key: PUBLIC_BASE_URL
        sync: false
